import type { Combo, Product } from "@/lib/types";

/**
 * Demo data mirrors supabase/seed.sql so the app can be browsed with zero
 * setup. Products carry `demo: true` for detection in isDemoData().
 */
const P = (
  slug: string,
  name_en: string,
  name_th: string,
  category: string,
  price: number,
  emoji: string,
  cities: string[] = ["all"],
  description = "",
): Product & { demo: true } => ({
  id: `demo-${slug}`,
  slug,
  name_en,
  name_th,
  category,
  price_thb: price,
  description,
  emoji,
  image_url: null,
  cities,
  is_active: true,
  created_at: new Date(2026, 0, 1).toISOString(),
  demo: true,
});

const C = (
  slug: string,
  title: string,
  description: string,
  steps: string,
  avg: number,
  count: number,
  items: Array<[string, number]>,
): Combo => ({
  id: `demo-${slug}`,
  slug,
  title,
  description,
  steps,
  photo_url: null,
  author_id: null,
  author_name: "Team 7Combo",
  avg_rating: avg,
  rating_count: count,
  created_at: new Date(2026, 0, 1).toISOString(),
  items: items.map(([ps, qty]) => ({
    combo_id: `demo-${slug}`,
    product_id: `demo-${ps}`,
    quantity: qty,
    notes: null,
    product: DEMO_PRODUCTS.find((p) => p.slug === ps),
  })),
});

export const DEMO_PRODUCTS: Array<Product & { demo: true }> = [
  P("fish-roe-tobiko", "Fish Roe (Tobiko) Pack", "ไข่ปลาโทบิโกะ", "frozen", 39, "🔴", ["bangkok", "chiangmai", "phuket"]),
  P("mayonnaise", "Mayonnaise (Kewpie-style)", "มายองเนส", "sauce", 35, "🥫"),
  P("imitation-crab-sticks", "Imitation Crab Sticks (chilled)", "เกาไหร่ / ปูอัด", "ready-to-eat", 20, "🦀"),
  P("mama-tom-yum", "Mama Tom Yum Goong (instant)", "มาม่า ต้มยำกุ้ง", "instant-noodles", 14, "🍜"),
  P("taro-fish-snack", "Taro Fish Snack (Original)", "ทาโร่ ปลาแท้", "snack", 10, "🐟"),
  P("vanilla-ice-cream-cup", "Vanilla Ice Cream Cup", "ไอศกรีมวานิลลา", "frozen", 15, "🍦"),
  P("cha-tra-mue-thai-milk-tea", "Cha Tra Mue Thai Milk Tea (bottle)", "ชาตรามือ", "drink", 29, "🧋"),
  P("mama-mala", "Mama Mala (instant)", "มาม่า หม่าล่า", "instant-noodles", 16, "🍜", ["bangkok", "chiangmai", "phuket", "pattaya"]),
  P("hard-boiled-eggs", "Hard-Boiled Eggs 2-pack", "ไข่ต้มสุก 2 ฟอง", "ready-to-eat", 15, "🥚"),
  P("fish-tofu-balls", "Fish Tofu Balls", "ลูกชิ้นปลา", "frozen", 30, "🐟"),
  P("sriracha-mayo-packet", "Sriracha Mayo Packet", "มายองเนสศรีราชา", "sauce", 10, "🥫"),
  P("butter-roll-bread", "Butter Roll Bread", "ขนมปังเนย", "dessert", 12, "🍞"),
  P("edamame", "Edamame (chilled pack)", "เอดามาเมะ", "ready-to-eat", 25, "🫛", ["bangkok", "chiangmai", "phuket", "pattaya"]),
  P("lays-salted-plum", "Lay's Norwegian Salted Plum", "เลย์ พลัมเค็ม", "snack", 20, "🥔"),
  P("calbee-shrimp-chips", "Calbee Shrimp Chips", "คาลบี กุ้ง", "snack", 20, "🍤"),
  P("oishi-green-tea-honey-lemon", "Oishi Green Tea Honey-Lemon", "โออิชิ ชาเขียว น้ำผึ้งมะนาว", "drink", 20, "🍵"),
  P("mango-sticky-rice", "Mango Sticky Rice (chilled)", "ข้าวเหนียวมะม่วง", "dessert", 45, "🥭"),
  P("coconut-ice-cream-cup", "Coconut Ice Cream Cup", "ไอศกรีมกะทิ", "frozen", 15, "🥥"),
  P("wai-wai-oriental", "Wai Wai Oriental Style", "ไวไว", "instant-noodles", 12, "🍜"),
  P("suki-sauce", "Suki Sauce", "น้ำจิ้มสุกี้", "sauce", 30, "🥫"),
  P("quail-eggs", "Quail Eggs (boiled, pack)", "ไข่นกกระทาต้ม", "ready-to-eat", 12, "🥚"),
];

export const DEMO_COMBOS: Combo[] = [
  C(
    "crab-stick-fish-roe-dip",
    "Crab Stick Fish Roe Dip",
    "The legendary viral hack: poppy fish roe folded into creamy mayo, dipped with ice-cold crab sticks.",
    "1. Chill the crab sticks and fish roe first — cold is essential.\n2. Squeeze the fish roe into a cup and add 2 big spoons of mayo.\n3. Stir until it turns sunset-pink and uniform.\n4. Peel the crab sticks, twist into bundles, and dip.",
    4.8,
    34,
    [["fish-roe-tobiko", 1], ["mayonnaise", 1], ["imitation-crab-sticks", 2]],
  ),
  C(
    "mama-tom-yum-crunch",
    "Mama Tom Yum Crunch",
    "Upgraded instant noodles: tom yum broth topped with crushed Taro fish snack for a crispy finish.",
    "1. Buy a Mama Tom Yum and a Taro fish snack.\n2. Crush the Taro packet inside its bag.\n3. Make the Mama with hot water at the counter.\n4. Pour half the crushed Taro over the noodles.",
    4.6,
    51,
    [["mama-tom-yum", 1], ["taro-fish-snack", 1]],
  ),
  C(
    "thai-tea-affogato",
    "Thai Tea Affogato",
    "Chilled vanilla ice cream drowned in Cha Tra Mue Thai milk tea. A 2-ingredient dessert that looks fancy.",
    "1. Grab a vanilla ice cream cup and a chilled Cha Tra Mue bottle.\n2. Open the ice cream and leave it in the cup.\n3. Pour the Thai tea slowly over the top.\n4. Wait 60 seconds, then eat before it fully melts.",
    4.4,
    27,
    [["vanilla-ice-cream-cup", 1], ["cha-tra-mue-thai-milk-tea", 1]],
  ),
  C(
    "mama-mala-protein-bomb",
    "Mama Mala Protein Bomb",
    "Mala instant noodles upgraded with a boiled egg and fish tofu balls — a proper meal for under ฿70.",
    "1. Start the Mama Mala with hot water and cover for 3 minutes.\n2. Halve the boiled eggs.\n3. Stir in the fish tofu balls while the noodles soften.\n4. Top with eggs and an extra drizzle of mala sauce.",
    4.5,
    19,
    [["mama-mala", 1], ["hard-boiled-eggs", 1], ["fish-tofu-balls", 1]],
  ),
  C(
    "sriracha-mayo-crab-roll",
    "Sriracha Mayo Crab Roll",
    "Butter roll bread stuffed with crab sticks and sriracha mayo — a 3-ingredient 'sushi roll' on the go.",
    "1. Mix the sriracha mayo packet with half the mayo.\n2. Toss the crab sticks through the sauce.\n3. Split the butter roll and stuff it.\n4. Wrap in the Lay's bag crumbs for extra crunch. (Optional but elite.)",
    4.2,
    23,
    [["sriracha-mayo-packet", 1], ["mayonnaise", 1], ["imitation-crab-sticks", 1], ["butter-roll-bread", 1]],
  ),
  C(
    "chiang-mai-izakaya-plate",
    "Chiang Mai Izakaya Plate",
    "Edamame + salted plum chips + shrimp chips + green tea. An izakaya-style grazing board for under ฿80.",
    "1. Chill everything first.\n2. Arrange edamame, Lay's salted plum, and shrimp chips on the hotel desk.\n3. Pour the Oishi green tea over ice.\n4. Salt the edamame with the leftover chip crumbs. Trust the process.",
    4.1,
    12,
    [["edamame", 1], ["lays-salted-plum", 1], ["calbee-shrimp-chips", 1], ["oishi-green-tea-honey-lemon", 1]],
  ),
  C(
    "mango-sticky-rice-sundae",
    "Mango Sticky Rice Sundae",
    "Warm the sticky rice, scoop the coconut ice cream on top — the Thai dessert, sundae-fied.",
    "1. Ask the counter to microwave the mango sticky rice for 30 seconds.\n2. Scoop the coconut ice cream on top.\n3. Let it melt into the rice for a minute.\n4. Eat with the little wooden spoon. Thank us later.",
    4.7,
    31,
    [["mango-sticky-rice", 1], ["coconut-ice-cream-cup", 1]],
  ),
  C(
    "sukiyaki-wai-wai-remix",
    "Sukiyaki Wai Wai Remix",
    "Drain most of the broth, stir in suki sauce for a thick, glossy, sweet-spicy 'dry' noodle with quail eggs.",
    "1. Make the Wai Wai with a little less water than usual.\n2. Drain about half the broth.\n3. Squeeze in the whole suki sauce sachet and stir.\n4. Halve the quail eggs on top and mix through.",
    3.9,
    15,
    [["wai-wai-oriental", 1], ["suki-sauce", 1], ["quail-eggs", 1]],
  ),
];
